# do not lint this file
# type: ignore

_.PixelData  # unused attribute (radstract/data/dicom/main.py:199) @
_.NumberOfFrames  # unused attribute (radstract/data/dicom/main.py:201)
_.Columns  # unused attribute (radstract/data/dicom/main.py:202)
_.Rows  # unused attribute (radstract/data/dicom/main.py:202)
_.TransferSyntaxUID  # unused attribute (radstract/data/dicom/main.py:207)
_.PlanarConfiguration  # unused attribute (radstract/data/dicom/main.py:208)
_.SamplesPerPixel  # unused attribute (radstract/data/dicom/utils.py:43)
_.PixelRepresentation  # unused attribute (radstract/data/dicom/utils.py:45)
_.BitsStored  # unused attribute (radstract/data/dicom/utils.py:46)
_.BitsAllocated  # unused attribute (radstract/data/dicom/utils.py:47)
_.HighBit  # unused attribute (radstract/data/dicom/utils.py:48)
_.MediaStorageSOPClassUID  # unused attribute (radstract/data/dicom/utils.py:56)
_.MediaStorageSOPInstanceUID  # unused attribute (radstract/data/dicom/utils.py:57)
_.ImplementationClassUID  # unused attribute (radstract/data/dicom/utils.py:58)
_.Manufacturer  # unused attribute (radstract/data/dicom/utils.py:60)
_.ImageType  # unused attribute (radstract/data/dicom/utils.py:61)
_.Modality  # unused attribute (radstract/data/dicom/utils.py:69)
_.SOPClassUID  # unused attribute (radstract/data/dicom/utils.py:72)
_.PhysicalDeltaX  # unused attribute (radstract/data/dicom/utils.py:75)
_.PhysicalDeltaY  # unused attribute (radstract/data/dicom/utils.py:78)
_.PixelSpacing  # unused attribute (radstract/data/dicom/utils.py:82)
_.SliceThickness  # unused attribute (radstract/data/dicom/utils.py:83)
_.ImageOrientationPatient  # unused attribute (radstract/data/dicom/utils.py:86)
_.ImagePositionPatient  # unused attribute (radstract/data/dicom/utils.py:89)
_.SeriesInstanceUID  # unused attribute (radstract/data/dicom/utils.py:98)
_.SOPInstanceUID  # unused attribute (radstract/data/dicom/utils.py:99)
_.StudyInstanceUID  # unused attribute (radstract/data/dicom/utils.py:100)
_.SeriesNumber  # unused attribute (radstract/data/dicom/utils.py:102)
_.PatientID  # unused attribute (radstract/data/dicom/utils.py:104)
_.StudyID  # unused attribute (radstract/data/dicom/utils.py:105)
